export const TEMPLATES=[
  {
    id:"software",
    icon:"⌨",
    name:"Software Dev",
    desc:"Engineering teams — sprints, tasks, code reviews",
    color:"#4F46E5",
    skills:["Frontend","Backend","DevOps","QA","Design","Data","Mobile","Security"],
    taskTypes:["Feature","Bug","DevOps","QA","Design","Research","Security"],
    exampleTasks:["Auth System","Dashboard UI","CI/CD Pipeline","API Rate Limiting","Mobile Nav"],
  },
  {
    id:"marketing",
    icon:"📣",
    name:"Marketing",
    desc:"Campaign teams — content, paid, SEO, analytics",
    color:"#059669",
    skills:["SEO","Paid Media","Email","Social","Analytics","Brand","Content","Strategy"],
    taskTypes:["Campaign","Content","SEO","Paid","Email","Analytics","Brand","Strategy"],
    exampleTasks:["Q2 Campaign","Blog Series","Google Ads","Email Nurture","Brand Refresh"],
  },
  {
    id:"creative",
    icon:"🎨",
    name:"Creative Agency",
    desc:"Creative teams — design, copy, motion, strategy",
    color:"#7C3AED",
    skills:["Copywriting","Art Direction","Motion","Strategy","Client Management","Photography","Video","Branding"],
    taskTypes:["Copy","Design","Motion","Strategy","Client","Photography","Video","Branding"],
    exampleTasks:["Brand Identity","Campaign Video","Website Copy","Social Assets","Pitch Deck"],
  },
  {
    id:"sales",
    icon:"💼",
    name:"Sales",
    desc:"Sales teams — pipeline, demos, accounts, closing",
    color:"#D97706",
    skills:["Prospecting","Demo","Closing","Account Management","Negotiation","Research","Onboarding","Support"],
    taskTypes:["Prospecting","Demo","Proposal","Negotiation","Onboarding","Support","Research","Account"],
    exampleTasks:["Enterprise Demo","Q3 Outreach","Contract Renewal","Product Walkthrough","Lead Qualification"],
  },
  {
    id:"construction",
    icon:"🏗",
    name:"Construction",
    desc:"Site teams — trades, project management, safety",
    color:"#DC2626",
    skills:["Project Management","Electrical","Plumbing","Structural","Safety","Surveying","Civil","Finishing"],
    taskTypes:["Planning","Electrical","Plumbing","Structural","Safety","Survey","Civil","Finishing"],
    exampleTasks:["Foundation Survey","Electrical Fit-out","Safety Audit","Structural Review","Site Planning"],
  },
  {
    id:"custom",
    icon:"⚙",
    name:"Custom",
    desc:"Define your own skill columns and task types",
    color:"#6B7280",
    skills:[],
    taskTypes:[],
    exampleTasks:[],
  },
];